-- This file is automatically generated, do not change it!
module Installation where

compilerName :: String
compilerName = "KiCS2 Curry -> Haskell Compiler"

installDir :: String
installDir = "c:/Users/Matthias/Documents/Uni/Master-Sem-4/Masterarbeit/kics2_windows"

majorVersion :: Int
majorVersion = 0

minorVersion :: Int
minorVersion = 2

revisionVersion :: Int
revisionVersion = 4

compilerDate :: String
compilerDate = "2013-04-05"

installDate :: String
installDate = "Mon Apr  8 15:34:50 GMT 2013"

runtime :: String
runtime = "ghc"

runtimeMajor :: Int
runtimeMajor = 7

runtimeMinor :: Int
runtimeMinor = 4

ghcExec :: String
ghcExec = "\"c:/Program Files (x86)/Haskell Platform/2012.2.0.0/bin/ghc.exe\" -no-user-package-conf -package-conf \"C:/Users/Matthias/AppData/Roaming/ghc/i386-mingw32-7.4.1/package.conf.d\""

ghcOptions :: String
ghcOptions = ""

installGlobal :: Bool
installGlobal = True
